# Generated by Django 4.0.5 on 2022-09-27 01:34

import RareFndApp.models
import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('image', models.ImageField(default='help.jpg', upload_to=RareFndApp.models.get_category_files_directory)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('phone_code', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, null=True)),
                ('head', models.TextField(max_length=280, null=True)),
                ('country', models.CharField(max_length=254, null=True)),
                ('address', models.CharField(max_length=254, null=True)),
                ('thumbnail', models.ImageField(default='help.jpg', null=True, upload_to=RareFndApp.models.get_project_files_directory)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('launch_date', models.DateTimeField(default=None, null=True)),
                ('deadline', models.DateTimeField(default=None, null=True)),
                ('fund_amount', models.FloatField(null=True)),
                ('description', ckeditor.fields.RichTextField(max_length=10000, null=True)),
                ('company_name', models.CharField(max_length=254, null=True)),
                ('company_nature_of_business', models.CharField(max_length=254, null=True)),
                ('company_address', models.CharField(max_length=254, null=True)),
                ('company_city', models.CharField(max_length=254, null=True)),
                ('company_zip_code', models.CharField(max_length=254, null=True)),
                ('company_country', models.CharField(max_length=254, null=True)),
                ('company_incorporation_date', models.DateTimeField(default=None, null=True)),
                ('company_registration_number', models.CharField(max_length=254, null=True)),
                ('company_estimated_annual_turnover', models.CharField(max_length=254, null=True)),
                ('company_tax_country', models.CharField(max_length=254, null=True)),
                ('company_tax_identification_number', models.CharField(max_length=254, null=True)),
                ('company_white_paper_url', models.CharField(max_length=1000, null=True)),
                ('company_tokenomics_url', models.CharField(max_length=1000, null=True)),
                ('company_ubos', models.JSONField(default=dict, null=True)),
                ('raised_amount', models.FloatField(blank=True, default=0, null=True)),
                ('rewarded_amount', models.FloatField(blank=True, default=0, null=True)),
                ('staking_address', models.CharField(blank=True, max_length=254, null=True)),
                ('staking_abi', models.TextField(blank=True, max_length=10000, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('project_live_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='RareFndData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_paper', models.FileField(upload_to=RareFndApp.models.get_rare_fnd_data_files_directory)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('price_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('wallet_address', models.CharField(blank=True, default='None', max_length=254, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('total_contributions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RareFndApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', ckeditor.fields.RichTextField(max_length=10000)),
                ('release_datetime', models.DateTimeField(auto_now_add=True)),
                ('release_amount', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RareFndApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=RareFndApp.models.get_project_files_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg', 'jpeg', 'xlsx', 'csv', 'pdf'])])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.subcategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.type'),
        ),
        migrations.CreateModel(
            name='PendingContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=254, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RareFndApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=254)),
                ('included_incentives', models.JSONField(default=list, null=True)),
                ('estimated_delivery', models.DateTimeField()),
                ('available_items', models.IntegerField()),
                ('price', models.FloatField()),
                ('reserved', models.IntegerField(blank=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RareFndApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_wallet_address', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.FloatField()),
                ('contribution_datetime', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=254, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RareFndApp.project')),
            ],
        ),
    ]
