# Generated by Django 4.0.5 on 2022-09-22 04:35

import RareFndApp.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='head',
            field=models.TextField(max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='raised_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rewarded_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='staking_abi',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='staking_address',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='help.jpg', null=True, upload_to=RareFndApp.models.get_project_files_directory),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
