# Generated by Django 4.0.5 on 2022-08-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentive',
            name='project',
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='reserved',
        ),
    ]
