# Generated by Django 4.0.5 on 2022-09-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0002_alter_project_address_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_country',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
