# Generated by Django 4.0.5 on 2022-08-20 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0002_remove_incentive_project_remove_incentive_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RareFndApp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentive',
            name='reserved',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
