# Generated by Django 4.0.5 on 2022-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='wallet_address',
            new_name='staking_address',
        ),
        migrations.AddField(
            model_name='project',
            name='staking_abi',
            field=models.TextField(default='aa', max_length=280),
            preserve_default=False,
        ),
    ]
