# Generated by Django 4.0.5 on 2022-09-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0003_project_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectData',
            field=models.JSONField(default=dict),
        ),
    ]
