# Generated by Django 4.0.5 on 2022-08-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0003_incentive_project_incentive_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='description',
            field=models.TextField(max_length=254),
        ),
    ]
