# Generated by Django 4.0.5 on 2022-08-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0004_rename_wallet_address_project_staking_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='staking_abi',
            field=models.TextField(max_length=10000),
        ),
    ]
