# Generated by Django 4.0.5 on 2022-09-24 08:18

import RareFndApp.models
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0006_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='company_address',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_city',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_country',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_estimated_annual_turnover',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_incorporation_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_nature_of_business',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_registration_number',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_tax_country',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_tax_identification_number',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_tokenomics_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_ubos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='company_white_paper_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_zip_code',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fund_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='head',
            field=models.TextField(max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_live_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='raised_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rewarded_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='staking_abi',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='staking_address',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.subcategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='help.jpg', null=True, upload_to=RareFndApp.models.get_project_files_directory),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.type'),
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=RareFndApp.models.get_project_files_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg', 'jpeg', 'xlsx', 'csv', 'pdf'])])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.project')),
            ],
        ),
    ]
