# Generated by Django 4.0.5 on 2022-09-11 21:57

import RareFndApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RareFndData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_paper', models.FileField(upload_to=RareFndApp.models.get_project_files_directory)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(upload_to=RareFndApp.models.get_project_files_directory),
        ),
    ]
