# Generated by Django 4.0.5 on 2022-09-11 22:20

import RareFndApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0007_rarefnddata_alter_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rarefnddata',
            name='white_paper',
            field=models.FileField(upload_to=RareFndApp.models.get_rare_fnd_data_files_directory),
        ),
    ]
