# Generated by Django 4.0.5 on 2022-09-11 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0008_alter_rarefnddata_white_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])]),
        ),
    ]
