# Generated by Django 4.0.5 on 2022-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0008_alter_project_company_incorporation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_ubos',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
