# Generated by Django 4.0.5 on 2022-09-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0009_alter_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='help.jpg', upload_to=''),
        ),
    ]
