# Generated by Django 4.0.5 on 2022-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0009_alter_project_company_ubos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='launch_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='raised_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rewarded_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='staking_abi',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='staking_address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
