# Generated by Django 4.0.5 on 2022-09-12 00:04

import RareFndApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0010_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='help.jpg', upload_to=RareFndApp.models.get_category_files_directory),
        ),
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(upload_to=RareFndApp.models.get_project_files_directory),
        ),
    ]
