# Generated by Django 4.0.5 on 2022-09-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0010_alter_project_creation_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='aproved',
            new_name='approved',
        ),
    ]
