# Generated by Django 4.0.5 on 2022-09-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0011_rename_aproved_project_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFiles',
            new_name='ProjectFile',
        ),
    ]
