# Generated by Django 4.0.5 on 2022-09-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0012_rename_projectfiles_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='included_incentives',
            field=models.JSONField(default=list, null=True),
        ),
    ]
