# Generated by Django 4.0.5 on 2022-09-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0013_alter_incentive_included_incentives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='estimated_delivery',
            field=models.DateTimeField(),
        ),
    ]
