# Generated by Django 4.0.5 on 2022-09-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0014_alter_incentive_estimated_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectData',
        ),
        migrations.AlterField(
            model_name='incentive',
            name='reserved',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
