# Generated by Django 4.0.5 on 2022-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0018_alter_project_company_incorporation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
        migrations.AlterField(
            model_name='project',
            name='company_incorporation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
