# Generated by Django 4.0.5 on 2022-10-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0019_eligiblecountry_remove_country_phone_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.CharField(default='AA', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(default='AA', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='nicename',
            field=models.CharField(default='AA', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='numcode',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phonecode',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='eligiblecountry',
            name='iso',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='eligiblecountry',
            name='iso3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='eligiblecountry',
            name='nicename',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eligiblecountry',
            name='numcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eligiblecountry',
            name='phonecode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='AA', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='eligiblecountry',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
