# Generated by Django 4.0.5 on 2022-10-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0021_alter_country_iso_alter_country_iso3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RareFndApp.eligiblecountry'),
        ),
    ]
