# Generated by Django 4.0.5 on 2022-10-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0023_alter_project_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_tax_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubo_company_tax_country', to='RareFndApp.eligiblecountry'),
        ),
    ]
