# Generated by Django 4.0.5 on 2022-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0027_alter_project_subscribed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_ubos',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
