# Generated by Django 4.0.5 on 2022-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0030_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_reward',
            field=models.IntegerField(default=0),
        ),
    ]
