# Generated by Django 4.0.5 on 2022-10-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0031_project_current_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_reward',
            field=models.FloatField(default=0),
        ),
    ]
