# Generated by Django 4.0.5 on 2022-11-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0032_alter_project_current_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
