# Generated by Django 4.0.5 on 2022-11-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0033_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
