# Generated by Django 4.0.5 on 2022-11-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0034_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_tokenomics_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_white_paper_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
