# Generated by Django 4.0.5 on 2022-11-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0035_alter_project_company_tokenomics_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company_tokenomics_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company_white_paper_url',
        ),
    ]
