# Generated by Django 4.0.5 on 2022-12-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0036_remove_project_company_tokenomics_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercuryo_pending_stake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(blank=True, default='None', max_length=254, null=True)),
                ('smart_contract_address', models.CharField(blank=True, default='None', max_length=254, null=True)),
                ('usd_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
