# Generated by Django 4.0.5 on 2022-12-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0037_mercuryo_pending_stake'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercuryo_pending_stake',
            name='bnb_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mercuryo_pending_stake',
            name='usd_amount',
            field=models.FloatField(default=0),
        ),
    ]
