# Generated by Django 4.0.5 on 2022-12-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0038_mercuryo_pending_stake_bnb_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercuryo_pending_stake',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
    ]
