# Generated by Django 4.0.5 on 2022-12-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0039_mercuryo_pending_stake_project_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mercuryo_pending_stake',
            new_name='MercuryoPendingStake',
        ),
    ]
