# Generated by Django 4.0.5 on 2022-12-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0040_rename_mercuryo_pending_stake_mercuryopendingstake'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercuryopendingstake',
            name='staking_transaction_hash',
            field=models.CharField(blank=True, default='None', max_length=254, null=True),
        ),
    ]
