# Generated by Django 4.0.5 on 2022-12-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0041_mercuryopendingstake_staking_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
