# Generated by Django 4.0.5 on 2023-01-06 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0045_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercuryopendingstake',
            name='contribution_datetime',
            field=models.DateTimeField(default=datetime.date(2023, 1, 6)),
        ),
    ]
