# Generated by Django 4.0.5 on 2023-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0048_project_wallet_address_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_method',
            field=models.CharField(default='FND', max_length=254),
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
