# Generated by Django 4.0.5 on 2023-01-24 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0050_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='eligible_for_selected_incentive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='selected_incentive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RareFndApp.incentive'),
        ),
        migrations.AddField(
            model_name='pendingcontribution',
            name='selected_incentive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RareFndApp.incentive'),
        ),
    ]
