# Generated by Django 4.0.5 on 2023-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0052_mercuryopendingstake_selected_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcontribution',
            name='Contribution_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
