# Generated by Django 4.0.5 on 2023-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0054_mercuryopendingstake_contributor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcontribution',
            name='Contributor_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
