# Generated by Django 4.0.5 on 2023-01-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0055_pendingcontribution_contributor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingcontribution',
            old_name='Contribution_amount',
            new_name='contribution_amount',
        ),
        migrations.RenameField(
            model_name='pendingcontribution',
            old_name='Contributor_email',
            new_name='contributor_email',
        ),
    ]
