# Generated by Django 4.0.5 on 2023-01-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0056_rename_contribution_amount_pendingcontribution_contribution_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MercuryoPendingStake',
        ),
    ]
