# Generated by Django 4.0.5 on 2023-03-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0057_delete_mercuryopendingstake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='head',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
