# Generated by Django 4.0.5 on 2023-05-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0058_alter_project_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
