# Generated by Django 4.0.5 on 2023-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0059_category_arabic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subheader',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
