# Generated by Django 4.0.5 on 2023-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0060_category_subheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='arabic_subheader',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
