# Generated by Django 4.0.5 on 2023-05-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RareFndApp', '0061_category_arabic_subheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
