# Generated by Django 4.1 on 2023-06-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0062_project_featured_project_recommended"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="fund_spend",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="owner_type",
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
