# Generated by Django 4.1 on 2023-06-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0063_project_fund_spend_project_owner_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owner_type",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
