# Generated by Django 4.1 on 2023-06-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0064_alter_project_owner_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="company_address",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_city",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_tax_country",
                to="RareFndApp.eligiblecountry",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_estimated_annual_turnover",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_incorporation_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_nature_of_business",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_registration_number",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_tax_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ubo_company_tax_country",
                to="RareFndApp.eligiblecountry",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_tax_identification_number",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_zip_code",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
