# Generated by Django 4.1 on 2023-06-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0065_alter_project_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
