# Generated by Django 4.1 on 2023-07-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0066_alter_project_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
