# Generated by Django 4.1 on 2023-07-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0067_project_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.CharField(
                blank=True,
                choices=[("30", "30 days"), ("60", "60 days"), ("90", "90 days")],
                default="30",
                max_length=2,
                null=True,
            ),
        ),
    ]
