# Generated by Django 4.1 on 2023-07-25 15:20

import RareFndApp.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0068_alter_project_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSVPSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "email",
                    RareFndApp.models.LowerCaseCharField(max_length=254, unique=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="company_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_company_tax_country",
                to="RareFndApp.eligiblecountry",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="company_tax_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_ubo_company_tax_country",
                to="RareFndApp.eligiblecountry",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="subscribed_users",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="project_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_type", models.CharField(blank=True, max_length=254, null=True)),
                ("title", models.CharField(max_length=254, null=True, unique=True)),
                ("head", models.TextField(max_length=500, null=True)),
                ("address", models.CharField(max_length=254, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        default="help.jpg",
                        null=True,
                        upload_to=RareFndApp.models.get_project_files_directory,
                    ),
                ),
                (
                    "creation_datetime",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("launch_date", models.DateTimeField(default=None, null=True)),
                (
                    "description",
                    ckeditor.fields.RichTextField(max_length=100000, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_nature_of_business",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_city",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_zip_code",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_incorporation_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "company_registration_number",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_estimated_annual_turnover",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_tax_identification_number",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("approved", models.BooleanField(default=True)),
                ("live", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("recommended", models.BooleanField(default=False)),
                (
                    "live_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="RareFndApp.category",
                    ),
                ),
                (
                    "company_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="RSVP_company_tax_country",
                        to="RareFndApp.eligiblecountry",
                    ),
                ),
                (
                    "company_tax_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ubo_company_tax_country",
                        to="RareFndApp.eligiblecountry",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="RareFndApp.eligiblecountry",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="RareFndApp.subcategory",
                    ),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="RSVP_Subscribers",
                        to="RareFndApp.rsvpsubscriber",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="RareFndApp.type",
                    ),
                ),
            ],
        ),
    ]
