# Generated by Django 4.1 on 2023-08-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0070_incentive_display_order_alter_rsvp_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ticket_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
