# Generated by Django 4.1 on 2023-08-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RareFndApp", "0071_project_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="head",
            field=models.TextField(max_length=600, null=True),
        ),
    ]
